# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.FileField(null=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='login_app.User'),
        ),
    ]
